// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"gin_admin_system/internal/app/api"
	"gin_admin_system/internal/app/dao/menu"
	"gin_admin_system/internal/app/router"
	"gin_admin_system/internal/app/service"
)

// Injectors from wire.go:

func BuildWireInject() (*Injector, func(), error) {
	db, cleanup, err := InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	menuRepo := &menu.MenuRepo{
		DB: db,
	}
	menuSrv := &service.MenuSrv{
		MenuRepo: menuRepo,
	}
	menuApi := &api.MenuApi{
		MenuSrv: menuSrv,
	}
	routerRouter := &router.Router{
		MenuApi: menuApi,
	}
	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		GinEngine: engine,
	}
	return injector, func() {
		cleanup()
	}, nil
}
